### ISSUE TITLE
Request fails when adding the `top_n_tokens` parameter

### ISSUE THREAD

**Issue by AIexanderDicke** [huggingface/text-generation-inference#1400]
### System Info

Adding the `top_n_tokens` parameter to a request results in an error. 

```
Traceback (most recent call last):
  File "/opt/conda/bin/text-generation-server", line 8, in <module>
    sys.exit(app())
  File "/opt/conda/lib/python3.10/site-packages/typer/main.py", line 311, in __call__
    return get_command(self)(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/typer/core.py", line 778, in main
    return _main(
  File "/opt/conda/lib/python3.10/site-packages/typer/core.py", line 216, in _main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/typer/main.py", line 683, in wrapper
    return callback(**use_params)  # type: ignore
  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/cli.py", line 89, in serve
    server.serve(
  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/server.py", line 228, in serve
    asyncio.run(
  File "/opt/conda/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
    handle._run()
  File "/opt/conda/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/opt/conda/lib/python3.10/site-packages/grpc_interceptor/server.py", line 165, in invoke_intercept_method
    return await self.intercept(
> File "/opt/conda/lib/python3.10/site-packages/text_generation_server/interceptor.py", line 21, in intercept
    return await response
  File "/opt/conda/lib/python3.10/site-packages/opentelemetry/instrumentation/grpc/_aio_server.py", line 82, in _unary_interceptor
    raise error
  File "/opt/conda/lib/python3.10/site-packages/opentelemetry/instrumentation/grpc/_aio_server.py", line 73, in _unary_interceptor
    return await behavior(request_or_iterator, context)
  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/server.py", line 100, in Prefill
    generations=[generation.to_pb() for generation in generations],
  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/server.py", line 100, in <listcomp>
    generations=[generation.to_pb() for generation in generations],
  File "/opt/conda/lib/python3.10/site-packages/text_generation_server/models/types.py", line 89, in to_pb
    return generate_pb2.Generation(
TypeError: Argument for field generate.v2.Generation.top_tokens is not iterable
```

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

1. Start any model: `docker run --gpus all --shm-size 1g -p 80:80 ghcr.io/huggingface/text-generation-inference:1.3.3 --model-id bigscience/bloom-560m --max-top-n-tokens 16`
2. The request with the json body
```
{
	"inputs": "1 + 2 = "
}
``` 
works, when the requests json body is changed to 
```
{
	"inputs": "1 + 2 = ",
	"parameters": 
	{
		"top_n_tokens": 4		
	}
}
```
one gets `424 Failed Dependency` with the error `Request failed during generation: Server error: Argument for field generate.v2.Generation.top_tokens is not iterable`. 

### Expected behavior

The second request works (it did with 1.1.0).

**Comment by AIexanderDicke** [comment]
Fixed #1497

**Comment by AIexanderDicke** [comment]
Fixed in this PR: https://github.com/huggingface/text-generation-inference/pull/1497

**Comment by SvenRohrTNG** [comment]
Hi!
This is still broken. If you launch TGI and run the default example request via swagger api, you will see a http 424.
I suggest to re-open the ticket, @Narsil  and @OlivierDehaene 

Related: https://github.com/huggingface/text-generation-inference/issues/1340

**Comment by SvenRohrTNG** [comment]
The issue is that according to https://github.com/huggingface/text-generation-inference/blob/17345402114e3d4a1f1c0a7fd650c734f7a992f9/proto/generate.proto#L159 Generation expects top_tokens to be of type Tokens, but in https://github.com/huggingface/text-generation-inference/blob/17345402114e3d4a1f1c0a7fd650c734f7a992f9/server/text_generation_server/models/types.py#L98 a list[Tokens] is used.
