### ISSUE TITLE
Salesforce/xgen-7b-8k-base

### ISSUE THREAD

**Issue by bgagandeep** [huggingface/text-generation-inference#560]
### Model description

The xgen 7b model in itself is a really fast model. Unfortunately being a noob in this field I don't understand the documentation very well. Happy to help create compatibility for this model if some guidance is given.

### Open source status

- [X] The model implementation is available
- [X] The model weights are available

### Provide useful links for the implementation

https://huggingface.co/Salesforce/xgen-7b-8k-base

**Comment by psinger** [comment]
I think the reason why xgen is not working here, is because it is a LLama model, but uses a different tokenizer. In TGI it is hardcoded to load `LlamaTokenizer` - exchanging this to `AutoTokenizer` should solve the issue.
https://github.com/huggingface/text-generation-inference/blob/main/server/text_generation_server/models/flash_llama.py#L39

**Comment by Narsil** [comment]
I just tried it , it doesn't solve the issue because some tensors are mismatched. 

Happy to receive PRs for better support, but we're not going to do it ourselves for now.

**Comment by jth3galv** [comment]
Following this issue.  Some comments that might be useful:

I am able to use the model through transformers library (as by instructions in the model card):

```
import torch
from transformers import AutoTokenizer, AutoModelForCausalLM

tokenizer = AutoTokenizer.from_pretrained("Salesforce/xgen-7b-8k-base", trust_remote_code=True)
model = AutoModelForCausalLM.from_pretrained("Salesforce/xgen-7b-8k-base", torch_dtype=torch.bfloat16)
inputs = tokenizer("The world is", return_tensors="pt")
sample = model.generate(**inputs, max_length=128)
print(tokenizer.decode(sample[0]))
```


but not through the **text-generation-inference** container. (I get the error about the wrong tokenizer)

It might be useful to read this discussion where the same problem was solved for **WebUI.**

https://huggingface.co/Salesforce/xgen-7b-8k-base/discussions/11

Any fix on this issue would be super great!

**Comment by Narsil** [comment]
> Any fix on this issue would be super great!

PRs are welcome.

**Comment by dongs0104** [comment]
> > Any fix on this issue would be super great!
> 
> PRs are welcome.

also run with 'trust_remote_code true'

**Comment by lckr** [comment]
I got it to work by changing `LlamaTokenizer` to `AutoTokenizer` in [flash_llama.py](https://github.com/huggingface/text-generation-inference/blob/main/server/text_generation_server/models/flash_llama.py#L39).

Another problem is that the xgen tokenizer changed the signature of `_decode` from `token_ids: Union[int, List[int]]` in the [hf implementation](https://github.com/huggingface/transformers/blob/fe861e578f50dc9c06de33cd361d2f625017e624/src/transformers/tokenization_utils_base.py#L3518C9-L3518C41) to `token_ids: List[int]` in [their own code](68f77decd61c12216d2a3e1b874daf1b1962525a).
As a result, when we iterate over batch elements in [flash_causal_lm.py](https://github.com/huggingface/text-generation-inference/blob/a2cf1bdb2fc0570dfca8b9ed2c8322f2040c3c07/server/text_generation_server/models/flash_causal_lm.py#L963C52-L963C64) and  call `batch_decode` with a list of ints their implementation leads to a shape mismatch error within tiktoken.
An ugly fix within `tgi` would be to replace [`batch_decode`](https://github.com/huggingface/text-generation-inference/blob/a2cf1bdb2fc0570dfca8b9ed2c8322f2040c3c07/server/text_generation_server/models/flash_causal_lm.py#L963C52-L963C64)  with decode.
But it's probably better to fix it at the source directly :)

**Comment by ChristophRaab** [comment]
> I got it to work by changing `LlamaTokenizer` to `AutoTokenizer` in [flash_llama.py](https://github.com/huggingface/text-generation-inference/blob/main/server/text_generation_server/models/flash_llama.py#L39).
> 
> Another problem is that the xgen tokenizer changed the signature of `_decode` from `token_ids: Union[int, List[int]]` in the [hf implementation](https://github.com/huggingface/transformers/blob/fe861e578f50dc9c06de33cd361d2f625017e624/src/transformers/tokenization_utils_base.py#L3518C9-L3518C41) to `token_ids: List[int]` in [their own code](68f77decd61c12216d2a3e1b874daf1b1962525a). As a result, when we iterate over batch elements in [flash_causal_lm.py](https://github.com/huggingface/text-generation-inference/blob/a2cf1bdb2fc0570dfca8b9ed2c8322f2040c3c07/server/text_generation_server/models/flash_causal_lm.py#L963C52-L963C64) and call `batch_decode` with a list of ints their implementation leads to a shape mismatch error within tiktoken. An ugly fix within `tgi` would be to replace [`batch_decode`](https://github.com/huggingface/text-generation-inference/blob/a2cf1bdb2fc0570dfca8b9ed2c8322f2040c3c07/server/text_generation_server/models/flash_causal_lm.py#L963C52-L963C64) with decode. But maybe using `batch_decode` instead of `decode` at this location (where we iterate over elements within a batch and don't decode the whole batch at once) could be also interpreted as a bug within tgi. :) If that is the case I would be happy to create an appropriate PR to fix that.

This seems to solve the issue.

**Comment by Narsil** [comment]
Very much **not in** favor of changing TGI code to accomodate a `trust_remote_code=True` model.
If they break `transformers` API, there's nothing we should do about it.

`LlamaTokenizerFast`  -> `AutoTokenizer` is innocuous enough that it's ok (even the preferential slow tokenizer is a relic from earlier hurdles between tokenizers, and because converting the slow to fast is really slow, which would hurt load performance).

**Comment by lckr** [comment]
I agree that `tgi` should not change to accommodate out-of-spec models.

@Narsil: Aside from the implementation differences in xgen, can you confirm that the current `tgi` implementation correctly uses [`batch_decode`](https://github.com/huggingface/text-generation-inference/blob/a2cf1bdb2fc0570dfca8b9ed2c8322f2040c3c07/server/text_generation_server/models/flash_causal_lm.py#L963C52-L963C64) in the [loop](https://github.com/huggingface/text-generation-inference/blob/a2cf1bdb2fc0570dfca8b9ed2c8322f2040c3c07/server/text_generation_server/models/flash_causal_lm.py#L904C8-L916C34) instead of `decode`? Looking at the code it seems to me as if `decode` might be what was originally intended at that line since we loop over the whole batch and want to decode each element in the batch individually here.

**Comment by Narsil** [comment]
Both should be equivalent here. Probably a relic as you say, or just some easier thing because of list/list of list use afterwards.

In any case, I will close this for now.
