### ISSUE TITLE
Endless stream of 'Waiting for shard 0 to be ready...'

### ISSUE THREAD

**Issue by ScientiaEtVeritas** [huggingface/text-generation-inference#81]
I tried to use `google/flan-t5-xxl` but repeadetly run into endless streams of "waiting for shard 0 to be ready":

Here's how I start it:

```
text-generation-launcher --model-id google/flan-t5-xxl --num-shard 1
```

```
2023-02-20T16:45:10.672340Z  INFO text_generation_launcher: Args { model_id: "google/flan-t5-xxl", revision: None, num_shard: 1, quantize: false, max_concurrent_requests: 128, max_input_length: 1000, max_batch_size: 32, max_waiting_tokens: 20, port: 3000, shard_uds_path: "/tmp/text-generation-server", master_addr: "localhost", master_port: 29500, huggingface_hub_cache: Some("/export/cache"), weights_cache_override: None, disable_custom_kernels: false, json_output: false, otlp_endpoint: None }
2023-02-20T16:45:10.672487Z  INFO text_generation_launcher: Starting download process.
2023-02-20T16:45:13.609322Z  INFO download: text_generation_launcher: "Files are already present in the local cache. Skipping download."
2023-02-20T16:45:14.079337Z  INFO text_generation_launcher: Successfully downloaded weights.
2023-02-20T16:45:14.079644Z  INFO text_generation_launcher: Starting shard 0
2023-02-20T16:45:24.091665Z  INFO text_generation_launcher: Waiting for shard 0 to be ready...
2023-02-20T16:45:34.101538Z  INFO text_generation_launcher: Waiting for shard 0 to be ready...
2023-02-20T16:45:44.111335Z  INFO text_generation_launcher: Waiting for shard 0 to be ready...
[...]
2023-02-20T17:12:06.346883Z  INFO text_generation_launcher: Waiting for shard 0 to be ready...
2023-02-20T17:12:16.361189Z  INFO text_generation_launcher: Waiting for shard 0 to be ready...
2023-02-20T17:12:26.376228Z  INFO text_generation_launcher: Waiting for shard 0 to be ready...
2023-02-20T17:12:36.389701Z  INFO text_generation_launcher: Waiting for shard 0 to be ready...
2023-02-20T17:12:46.403412Z  INFO text_generation_launcher: Waiting for shard 0 to be ready...
2023-02-20T17:12:56.417555Z  INFO text_generation_launcher: Waiting for shard 0 to be ready...
```

I don't see any activity on the GPU, so it's not busy with loading the model onto the GPU.

Maybe, is there some way to get more verbose output to see where it's hanging?

**Comment by OlivierDehaene** [comment]
What commit are you on? It doesn't seem to be the latest one.

**Comment by ScientiaEtVeritas** [comment]
I'm on the latest release at least (v0.3.0, c720555adc4ea192a55c101deafcd96daa8ee6b1).

**Comment by OlivierDehaene** [comment]
I published a new release. Can you try with this one? 
I was unable to reproduce your issue on my end.

**Comment by OlivierDehaene** [comment]
Closing as stale.

**Comment by ScientiaEtVeritas** [comment]
I still have this problem, even with the latest commit. Most recently, it happens with `text-generation-lau
ncher --model-id facebook/galactica-120b --num-shard 1 --quantize` for me.

**Comment by nicolasf** [comment]
Same issue here. While it's trying to load the GPU usage is maxed out, but VRAM usage is low (around 1.5GB)

**Comment by nicolasf** [comment]
Same issue here. While it's trying to load the GPU usage is maxed out, but VRAM usage is low (around 1.5GB)

**Comment by OlivierDehaene** [comment]
Yes, if you see that only a fraction of the GPUs have a 100% GPU utilization, but the other ones are idle it is usually a NCCL issue.
